server:
  host: 0.0.0.0
  port: 8080
webrtc:
  stun_servers:
  - stun:stun.l.google.com:19302
  turn: ''
  turn_username: ''
  turn_password: ''
video:
  width: 960
  height: 540
  fps: 25
  bitrate: 1200000
  mirror: horizontal
  rotate: 180
  flip: rotate-180
