video:
  width: 1280
  height: 720
  fps: 30
  bitrate: 2500000
  flip: none  # none|horizontal|vertical
webrtc:
  stun_servers:
    - stun:stun.l.google.com:19302
  # turn: ""
  # turn_username: ""
  # turn_password: ""
server:
  host: 0.0.0.0
  port: 8080
